### ISSUE TITLE
Maximum VPC size

### ISSUE THREAD

**Issue by marfire** [edgarroman/zappa-django-guide#1]
Thank you very much for writing this excellent guide. Having just the read the whole thing, let me provide a few suggestions.

[This section](https://edgarroman.github.io/zappa-django-guide/aws_network_primer/#first-there-is-a-vpc) says:

> Generally common practice is to use the 10.0.0.0/8 private network space. Creating a VPC with 10.0.0.0/8 network range will allow you to use over 16 million IP addresses.

According to [the AWS documentation](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#VPC_Sizing):

> You can assign a single CIDR block to a VPC. The allowed block size is between a /16 netmask and /28 netmask. In other words, the VPC can contain from 16 to 65,536 IP addresses.

**Comment by edgarroman** [comment]
Thanks - updated to have max VPC size
