### ISSUE TITLE
topic request: using the zappa-managed cloudwatch logging

### ISSUE THREAD

**Issue by monkeypants** [edgarroman/zappa-django-guide#10]
this is a wonderful guide that has been very useful to me.

After working through it, I would like to know how to configure my suite to use the cloudwatch logging that is managed via zappa. I guess using watchtower would bypass the zappa-managed cloudwatch configuration (I don't want to do that), so how to proceed?

**Comment by edgarroman** [comment]
Thanks @monkeypants.  So help me with a little clarification.  When you say configure zappa to use CloudWatch, what do you mean?  What's the goal here?  Is it to easily get these log messages?  or filter them? or use a different dashboard view to get an overview?

**Comment by monkeypants** [comment]
When I package and deploy with zappa I want to configure my django logging subsystem to write to cloudwatch. What's the story with that?

I thought maybe this watchtower thing https://github.com/kislyuk/watchtower but haven't tried it. My concern is that would not respect zappa_settings for "cloudwatch_log_level". Maybe this is not important, maybe the zappa_settings cloudwatch_* config is only for apigw stuff, maybe my request is based on a misunderstanding around that. I.e. sort out your own logging and do it the way you want it.

How this came up is trying to get django-helpdesk to work in zappa. One part of it is trying to write some logs to a hardcoded path (yuck). Problem is that the paths it's writing to don't exist in lambda, so it's failing in a messy way that breaks other things. A quick fix is to switch hardcoded paths to /tmp/, and that did solve my immediate problem but I loose those logs. I think the proper fix is to refactor it to use the django logging subsystem, and set up logging properly for the whole site. So I went to your guide again to look for the logging section and found there wasn't one.

**Comment by edgarroman** [comment]
Definitely worth a section.  In the meantime you are on the right track to configure Django to output to stderr and stdout and you should be able to get logs via zappa tail / watchtower / etc

**Comment by kevinluvian** [comment]
hi @monkeypants @edgarroman did u guys manage to integrate watchtower with zappa? can you please explain how did u do it?

**Comment by monkeypants** [comment]
I didn't end up using watchtower, sorry. I just used STDOUT.

**Comment by edgarroman** [comment]
@monkeypants Can you talk a bit more about that?  What would be the advantages of using watchtower vs STDOUT?

**Comment by monkeypants** [comment]
I was being lazy and didn't investigate watchtower enough to say it was a well reasoned decision. I just kludged all the code that was logging to magic file names and made it log to STDOUT instead.

Like you suggested above @edgarroman, this meant I could see log events in `zappa tail` which was sufficient for my purposes (debugging).

**Comment by edgarroman** [comment]
Alright then, I will close this issue unless there is a compelling reason to keep it open...
