### ISSUE TITLE
Local dev 

### ISSUE THREAD

**Issue by antat2003** [edgarroman/zappa-django-guide#13]
Hi guys
Can i run local python manage.py runserver to test it locally before update to dev env? I don't want to waste time waiting for it to complete upload/packaging/... every time small change is made. 
Thank you
An

**Comment by edgarroman** [comment]
Yes!  You can do a runserver locally or even within your docker environment (https://blog.zappa.io/posts/docker-zappa-and-python3).  the trick will be if your app is database driven, then you will need a copy of the database locally or the ability to remotely connect to your hosted database
