### ISSUE TITLE
How to send Emails?

### ISSUE THREAD

**Issue by weasteam** [edgarroman/zappa-django-guide#16]
Would you please add documentation on how to send emails? It would be great to be able to do it with Zappa task.

**Comment by edgarroman** [comment]
Sure but in the meantime, it's pretty straightforward:

`zappa_settings.json`
```
       "events" : [
            {
                "function" : "yourproject.yourapp.triggerSendNotifications",
                "expression" : "rate(6 hours)"
            }
        ], 
```

`yourapp.py`
```
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string

def triggerSendNotifications():
    from_email = settings.EMAIL_FROM
    subject = 'This is the subject'

    # Gather information for body   
    context = { 'name' : 'Jim' }
    text_content = render_to_string('email/updated.txt', context)
    html_content = render_to_string('email/updated.html', context)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [user.email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
```

`updated.html`
```
Dear {{name}},
This is an <b>HTML</b> email. 
```

`updated.text`
```
Dear {{name}},
This is a text email. 
```

**Comment by weasteam** [comment]
@edgarroman 

Thanks for the reply, but that is not what I mean. I mean how to configure the zappa environment to enable send emails.

It turns out the lambda created by zappa, which inside a vpc, does not have internet access. So there is no way to send emails out. I resolved this by adding a public subnet to VPC (or NAT Gateway).

**Comment by edgarroman** [comment]
I misunderstood - it seems you merely needed the lambda function to have external network connectivity.  That is already covered in the guide.  Thanks for the feedback.
