### ISSUE TITLE
ENIs and public routability

### ISSUE THREAD

**Issue by marfire** [edgarroman/zappa-django-guide#2]
[This sentence](https://edgarroman.github.io/zappa-django-guide/aws_network_primer/#general-behavior-and-internet-access) gave me pause:

> But ENIs are not publicly routable, so the Lambda function will not be able to access the Internet directly.

ENIs, in general, are publicly routable, this is a Lambda restriction. So I suggest: "But ENIs in Lambda are not publicly routable...".

**Comment by edgarroman** [comment]
Yes, good area to clarify.  The ENIs are interesting with respect to other subnet resources like peer EC2 instances, but the Lambda limitation is worth calling out explicitly.
