### ISSUE TITLE
makemigrations

### ISSUE THREAD

**Issue by johnedstone** [edgarroman/zappa-django-guide#22]
First of all, thank you for a terrific tutorial
My question is this.  I have set up my environment with Approach #2, Docker with zappa.  I have set up the VPC, public with private subnets.  I have set up the Postgres DB.  Running python manage.py makemigrations fails because of course the DB is on a private subnet.  Of course, zappa manage migrate works, and creating superuser works as you've described.  Even zappa manage makemigrations works.  But this last command doesn't write the migrations locally.  So what's the work around: expose the DB publically?

**Comment by edgarroman** [comment]
For migrations, I would suggest that you have a local database (sqlite is usually sufficient).  And ensure the local database schema matches what you have in the VPC Postgres.  Then anytime you make schema changes:
1. Make the migrations in the docker environment - this should generate the migration files in each django app
2. Do a zappa update to deploy the new migration files to your vpc lambdas
3. Run zappa manage migrate to apply those schema changes to your VPC Postgres.

The only gotcha here is if your db migrations take longer than 5 minutes.  This would be unusual, but could happen in some circumstances (e.g. you are adding a default value to a column in a table with many rows).  In those cases, you would have to perform migrations from a non-lambda environment.  Some possibilities:
a. Run an EC2 instance in your VPC and setup your development environment there
b. Connect remotely to the Postgres DB via a bastion host or directly from your computer.

Hope that helps

**Comment by johnedstone** [comment]
Okay, thanks!

- I've always wondered if sqlite makemigrations were the same as if you did it with postgres, so that assumes that's true.
- Is there a Flask tutorial, of all the ones suggested in the Zappa Guides section, that is very similar to yours?  I'm new to Flask, and would like to work through one of those?

**Comment by edgarroman** [comment]
Glad I could help. 
Sorry, I'm not sure there is one for Flask, but this one covers many of the common overlaps (e.g. basic python setup, etc)

**Comment by johnedstone** [comment]
Ok, thanks again.
-- Ed


-------------------------
Ed Johnstone    Ô¿Ô¬
cell: 317.331.1848
email: johnedstone@gmail.com
*'Discouragement is never from God, as it clouds faith and hope' - St
Ignatius*

*'Be the first to love' - Chiara Lubich*

**Comment by liperbr** [comment]
> For migrations, I would suggest that you have a local database (sqlite is usually sufficient). And ensure the local database schema matches what you have in the VPC Postgres. Then anytime you make schema changes:
> 
> 1. Make the migrations in the docker environment - this should generate the migration files in each django app
> 2. Do a zappa update to deploy the new migration files to your vpc lambdas
> 3. Run zappa manage migrate to apply those schema changes to your VPC Postgres.
> 
> The only gotcha here is if your db migrations take longer than 5 minutes. This would be unusual, but could happen in some circumstances (e.g. you are adding a default value to a column in a table with many rows). In those cases, you would have to perform migrations from a non-lambda environment. Some possibilities:
> a. Run an EC2 instance in your VPC and setup your development environment there
> b. Connect remotely to the Postgres DB via a bastion host or directly from your computer.
> 
> Hope that helps

How could I integrate that workaround in my CI/CD?
