### ISSUE TITLE
API gateway & Route53 point to cloudfront, but there's nothing in cloudfront

### ISSUE THREAD

**Issue by jayenashar** [edgarroman/zappa-django-guide#34]
I believe I have successfully completed https://edgarroman.github.io/zappa-django-guide/walk_domain/#option-1-route53-and-acm .  I can see in the AWS console for API Gateway and Route53 that they point to the same cloudfront target, yet there is nothing in cloudfront (also the cloudfront DNS entry doesn't exist).

Is the 40 minute wait only for HTTPS?  Or will it also set up cloudfront after 40 minutes?

![https://console.aws.amazon.com/cloudfront/home](https://user-images.githubusercontent.com/1137152/51886095-65dbde80-23e2-11e9-90bb-3e0c68e5af0c.png)

**Comment by edgarroman** [comment]
The cloudfront distro associated with the zappa API gateway is hidden from the CF distro tool and is exclusively associated with the API gateway.  In addition, you cannot configure any settings on it.

**Comment by jayenashar** [comment]
thanks.  i might write some words to that effect in the docs.
