### ISSUE TITLE
Expand on why you might want a custom CloudFront distribution

### ISSUE THREAD

**Issue by marfire** [edgarroman/zappa-django-guide#5]
The section on [managing your own CloudFront distribution](https://edgarroman.github.io/zappa-django-guide/walk_domain/) left me unsure of what the benefits are.

The only benefit mentioned is caching. But Django has its own support for specifying HTTP cache headers, and I think it's fair to say that Zappa users want to leverage their framework rather than use AWS-specific mechanisms where possible. Does CloudFront allow more or better control of caching than I can achieve from within Django (or other frameworks)?

If you know of other benefits of using a CloudFront distribution, it would be great to add them.

(Another thing that stuck out to me was that three paragraphs of text are repeated verbatim, [here](https://edgarroman.github.io/zappa-django-guide/walk_domain/#choices) and [here](https://edgarroman.github.io/zappa-django-guide/walk_domain/#manage-your-own-cloudfront-distribution). It might be better to shorten and summarize the first one.)

**Comment by edgarroman** [comment]
I think I need a good editor 😄   - will add additional reasons

**Comment by edgarroman** [comment]
This was a good suggestion - I think there are many good reasons to use a custom distro.

**Comment by marfire** [comment]
Good list!

Under *Enhanced Security* you might also want to mention that CloudFront can serve static files over HTTPS, unlike S3.

I found a couple typos which I marked on the PR.

**Comment by edgarroman** [comment]
Thanks for the sharp eyes!  I didn't add the HTTPS comment because despite the AWS omitting this, the HTTPS on S3 static files seem to work fine.
