### ISSUE TITLE
Should we turn this aspects of this guide into a helper application?

### ISSUE THREAD

**Issue by Miserlou** [edgarroman/zappa-django-guide#6]
There is so much goodness in this guide, but I'm wondering if we can make people's lives easier by packaging this stuff into some helper libraries. In particular, the ability to create the database and to create a superuser?

Any thoughts on that?

**Comment by Miserlou** [comment]
Welp, I went ahead and did this anyway: https://github.com/Miserlou/zappa-django-utils

**Comment by edgarroman** [comment]
Aw Dag - my notifications were not turned on for this repo.  I did see you made the utils.  I will reference it in the docs

**Comment by monkeypants** [comment]
I think this ticket is done (can be closed), amirite?
