### ISSUE TITLE
S3 bucket needs to be created?

### ISSUE THREAD

**Issue by ceefour** [edgarroman/zappa-django-guide#7]
https://github.com/edgarroman/zappa-django-guide/blame/master/docs/walk_core.md#L53 mentions precreating the S3 bucket, but there's no instruction above about it.

**Comment by edgarroman** [comment]
You're right - thanks!

**Comment by edgarroman** [comment]
Permissions will be handled by the zappa tool, but essentially you need the IAM user running the zappa tool to have full control of the s3 bucket.  No public access needed

**Comment by jayenashar** [comment]
sorry i thought this issue was for the static bucket.  i understand zappa sets up the lambda bucket ok.
